[Global]
Name = ngircd.test.server
AdminEMail = admin@irc.server
Info = Windows test server
Listen = 127.0.0.1
Ports = 6789
MotdFile = ./ngircd.motd
HelpFile = ./original/doc/Commands.txt
PidFile = C:/develop/ngircd/runtime/ngircd.pid
Network = testnet

[Limits]
MaxConnections = 32
MaxConnectionsIP = 4
MaxJoins = 4
MaxNickLength = 15

[Options]
ConnectIPv4 = yes
ConnectIPv6 = no
DNS = no
MorePrivacy = no
NoticeBeforeRegistration = yes
ScrubCTCP = yes
